# Application name
spring.application.name=jerusalem-api
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

# Disable Spring Boot DevTools restart
spring.devtools.restart.enabled=false

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/jerusalem_db
spring.datasource.username=root
spring.datasource.password=wuqd!12ndIUBOB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# Server port configuration
server.port=9090


# jwt token for authentication
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000